#!/usr/bin/env python3
import datetime
import sys

import pandas as pd

def main():
    args = sys.argv
    if len(args) != 2:
        print("Must specify file name")
        exit(1)

    df = pd.read_csv(args[1])

    renaming_columns = {
        "Started Date": "date",
        "Amount": "amount",
        "Description": "note",
    }

    df["Amount"] -= df["Fee"]
    df = df[renaming_columns.keys()]
    df.rename(
        inplace=True,
        columns=renaming_columns,
    )
    df["date"] = pd.to_datetime(df["date"]).map(lambda x: x.isoformat())

    df["account"] = "Personal"
    df["category"] = "Unspecified"

    print(df.to_csv(
        index=False,
    ))


if __name__ == '__main__':
    main()
