#!/usr/bin/env python3
import datetime
import sys

import pandas as pd


def main():
    args = sys.argv
    if len(args) != 2:
        print("Must specify file name")
        exit(1)

    df = pd.read_csv(args[1])

    df = df[df['Beschreibung'] != "Gesamtbilanz"]

    renaming_columns = {
        "Datum": "date",
        "Kosten": "total amount",
        "Beschreibung": "note",
        "Währung": "currency",
        "Elwin Stephan": "my share",
        "Kosten": "total amount",
    }

    df = df[renaming_columns.keys()]
    df.rename(
        inplace=True,
        columns=renaming_columns,
    )
    df["date"] = pd.to_datetime(df["date"]).map(lambda x: x.isoformat())
    df["my share"] = df["my share"].astype('float64')
    df["total amount"] = df["total amount"].astype('float64')
    mask = df["my share"] > 0
    df["amount"] = df[mask]["total amount"] - df[mask]["my share"] + df[~mask]["my share"] * -1
    df.loc[mask, "amount"] = df.loc[mask, "total amount"] - df.loc[mask, "my share"]
    df.loc[~mask, "amount"] = df.loc[~mask, "my share"] * -1

    df["account"] = "Personal"
    df["category"] = "Unspecified"
    df["amount"] = df["amount"].round(decimals=2) * -1

    print(df.to_csv(
        index=False,
    ))


if __name__ == '__main__':
    main()
