#!/usr/bin/env python3
import datetime
import sys

import pandas as pd


def main():
    args = sys.argv
    if len(args) != 2:
        print("Must specify file name")
        exit(1)

    df = pd.read_csv(args[1])

    df = df[df['Beschreibung'] != "Gesamtbilanz"]

    renaming_columns = {
        "Datum": "date",
        "Elwin Stephan": "amount",
        "Beschreibung": "note",
        "Währung": "currency"
    }

    df = df[renaming_columns.keys()]
    df.rename(
        inplace=True,
        columns=renaming_columns,
    )
    df["date"] = pd.to_datetime(df["date"]).map(lambda x: x.isoformat())
    df["amount"] = -df["amount"].astype('float64').abs()

    df["account"] = "Personal"
    df["category"] = "Unspecified"
    df["amount"] = df["amount"].round(decimals=2)

    print(df.to_csv(
        index=False,
    ))


if __name__ == '__main__':
    main()
